export * from './Header/Header';
export * from './MovieInfo/MovieInfo';
export * from './MoviesList/MoviesList';
export * from './UserInfo/UserInfo';
export * from './StarsRating/StarsRating';
export * from './GenreNav/GenreNav';
export * from './Footer/Footer';
export * from './TopMovie/TopMovie';
export * from './Upcoming/Upcoming';
export * from './GenresPage/GenresPage';
export * from './SearchPage/SearchPage';
export * from './TvPage/TvPage';
export * from './LatestPage/LatestPage';
export * from './OrderdescPage/OrderdescPage';
export * from './SearchPage/SearchPage';
export * from './LatestPage/LatestPage'
export * from './StarsRating/StarsRating'
export * from './Layout/Layout'